/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesos;

import static java.lang.String.valueOf;

/**
 *
 * @author dalonsoperez
 */
public class Ventana extends javax.swing.JFrame {
    
    Double valor;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        EntradaPesosA = new javax.swing.JTextField();
        EntraPesoC = new javax.swing.JTextField();
        TextoPesosC1 = new javax.swing.JLabel();
        TextoPesoA1 = new javax.swing.JLabel();
        SalidaPesoA = new javax.swing.JLabel();
        Convertir1 = new javax.swing.JButton();
        TextoPesosA2 = new javax.swing.JLabel();
        SalidaPesoC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Convertir2 = new javax.swing.JButton();
        Separador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("x");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 12, -1, -1));
        getContentPane().add(EntradaPesosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 40));

        EntraPesoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntraPesoCActionPerformed(evt);
            }
        });
        getContentPane().add(EntraPesoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 40));

        TextoPesosC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoPesosC1.setText("Pesos Colombianos");
        getContentPane().add(TextoPesosC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        TextoPesoA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoPesoA1.setText("Pesos Argentinos");
        getContentPane().add(TextoPesoA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, 40));

        SalidaPesoA.setBackground(new java.awt.Color(255, 255, 255));
        SalidaPesoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(SalidaPesoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, 40));

        Convertir1.setText("Convertir");
        Convertir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Convertir1ActionPerformed(evt);
            }
        });
        getContentPane().add(Convertir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        TextoPesosA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoPesosA2.setText("Pesos Argentinos");
        getContentPane().add(TextoPesosA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 40));

        SalidaPesoC.setBackground(new java.awt.Color(255, 255, 255));
        SalidaPesoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(SalidaPesoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 160, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesos Colombianos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 160, 40));

        Convertir2.setText("Convertir");
        Convertir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Convertir2ActionPerformed(evt);
            }
        });
        getContentPane().add(Convertir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        Separador.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout SeparadorLayout = new javax.swing.GroupLayout(Separador);
        Separador.setLayout(SeparadorLayout);
        SeparadorLayout.setHorizontalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        SeparadorLayout.setVerticalGroup(
            SeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 410, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void EntraPesoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntraPesoCActionPerformed
        
    }//GEN-LAST:event_EntraPesoCActionPerformed

    private void Convertir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Convertir1ActionPerformed
        valor = Double.parseDouble(EntraPesoC.getText());
        valor = (valor*15.40)/2919;
        SalidaPesoA.setText(valueOf(valor)+"$");
    }//GEN-LAST:event_Convertir1ActionPerformed

    private void Convertir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Convertir2ActionPerformed
        valor = Double.parseDouble(EntradaPesosA.getText());
        valor = (valor*2919)/15.40;
        SalidaPesoC.setText(valueOf(valor)+"$");
    }//GEN-LAST:event_Convertir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convertir1;
    private javax.swing.JButton Convertir2;
    private javax.swing.JTextField EntraPesoC;
    private javax.swing.JTextField EntradaPesosA;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel SalidaPesoA;
    private javax.swing.JLabel SalidaPesoC;
    private javax.swing.JPanel Separador;
    private javax.swing.JLabel TextoPesoA1;
    private javax.swing.JLabel TextoPesosA2;
    private javax.swing.JLabel TextoPesosC1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
